hantu:
  api_key: 'PSr1LEPrEqbKEn3MY2qEkM035Gg2VSBgHKev'
  secret_key: 'MOrypulpG3csIod3fNE1KIkpzM9369XcLiUm6IEDQ+93HuKT8+V+iGcank0b8Do4YTcVHBGrlPM60XDZtLj1uhXWPyLJCqYGb+DJtFZNi51/Aijs+4b9h1AAaVb05lPcs/5Oxw2tDN/uW8/CUj8tZi2MzF7O8ShpkFFMM5D2ANrlO9uyehw='
  account_id: '50161255'
  htsid: '@2821704'
